package simizer.laws;

/**
 * A {@code Law} representing a distribution that always returns the same value.
 */
public class ConstantLaw extends Law {

  /** The value that this Law should return. */
  private final int value;

  /**
   * Initializes an instance of the class.
   *
   * @param value the value generated by this distribution
   */
  public ConstantLaw(int value) {
    super();

    this.value = value;
  }

  @Override
  protected int generateNextValue() {
    return value;
  }
}
